;;; gruvbox-theme.el --- Minimal Gruvbox theme (Classic base, Material mode-line/org) -*- lexical-binding: t -*-

;; Author: Ziad
;; A slimmed-down, dark-only build of gruvbox-material-emacs.
;; Base palette: Classic / medium contrast.
;; Mode-line and org-mode faces are overridden to the Material palette.
;; No palette switching, no gm/config menu, no light variant.

;;;###autoload
(deftheme gruvbox
  "Gruvbox Classic theme, with mode-line and org-mode kept on Material colors.")

(custom-theme-set-faces
 'gruvbox
 '(default ((t (:background "#282828" :foreground "#ebdbb2"))))
 '(bold    ((t (:foreground "#83a598" :weight bold))))
 '(cursor ((t (:background "#ebdbb2"))))
 '(fringe ((t (:background "#282828" :foreground "#928374"))))
 '(hl-line ((t (:background "#3c3836"))))
 '(region ((t (:background "#2D4F4F"))))
 '(secondary-selection ((t (:background "#504945"))))
 '(vertical-border ((t (:foreground "#504945"))))
 '(fill-column-indicator ((t (:background "#3c3836" :foreground "#3c3836"))))
 '(minibuffer-prompt ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(link ((t (:foreground "#83a598" :underline t))))
 '(link-visited ((t (:foreground "#d3869b" :underline t))))
 '(highlight ((t (:background "#2D4F4F"))))
 '(lazy-highlight ((t (:background "#3B3116" :foreground "#ebdbb2"))))
 '(isearch ((t (:background "#2D4F4F" :foreground "#fbf1c7" :weight bold))))
 '(isearch-fail ((t (:background "#402120" :foreground "#fb4934"))))
 '(match ((t (:background "#34381b" :foreground "#ebdbb2"))))
 '(show-paren-match ((t (:background "#2D4F4F" :foreground "#fabd2f" :weight bold))))
 '(show-paren-mismatch ((t (:background "#402120" :foreground "#fb4934" :weight bold))))
 '(shadow ((t (:foreground "#928374"))))
 '(error ((t (:foreground "#fb4934" :weight bold))))
 '(warning ((t (:foreground "#fabd2f" :weight bold))))
 '(success ((t (:foreground "#b8bb26" :weight bold))))
 '(button ((t (:foreground "#83a598" :underline t))))
 '(header-line ((t (:background "#504945" :foreground "#ebdbb2"))))
 '(header-line-highlight ((t (:background "#665c54" :foreground "#ebdbb2"))))
 '(help-key-binding ((t (:foreground "#8ec07c" :background "#504945" :box (:line-width 1 :color "#665c54")))))
 '(homoglyph ((t (:foreground "#8ec07c"))))
 '(nobreak-hyphen ((t (:foreground "#fb4934"))))
 '(escape-glyph ((t (:foreground "#8ec07c"))))
 '(completions-common-part ((t (:foreground "#8ec07c" :weight bold))))
 '(completions-first-difference ((t (:foreground "#fabd2f" :weight bold))))
 '(completions-annotations ((t (:foreground "#7c6f64" :slant italic))))
 '(widget-field ((t (:background "#504945" :foreground "#ebdbb2"))))
 '(widget-button ((t (:foreground "#83a598" :weight bold))))
 '(tooltip ((t (:background "#665c54" :foreground "#fbf1c7"))))
 '(line-number ((t (:background "#282828" :foreground "#7c6f64" :inherit fixed-pitch :height 1.0))))
 '(line-number-current-line ((t (:background "#282828" :foreground "#fabd2f" :weight bold :inherit fixed-pitch :height 1.0))))
 '(mode-line ((t (:background "#3A3735" :foreground "#d5be98" :box (:line-width 1 :color "#504945")))))
 '(mode-line-inactive ((t (:background "#2B2B2B" :foreground "#928374" :box (:line-width 1 :color "#504945")))))
 '(mode-line-buffer-id ((t (:foreground "#ddc7a1" :weight semi-bold))))
 '(mode-line-emphasis ((t (:foreground "#ddc7a1" :weight semi-bold))))
 '(mode-line-highlight ((t (:foreground "#e78a4e"))))
 '(tab-bar ((t (:background "#282828" :foreground "#928374"))))
 '(tab-bar-tab ((t (:background "#504945" :foreground "#ebdbb2" :weight semi-bold :box (:line-width 1 :color "#665c54")))))
 '(tab-bar-tab-inactive ((t (:background "#282828" :foreground "#928374" :box (:line-width 1 :color "#504945")))))
 '(tab-line ((t (:background "#282828" :foreground "#928374"))))
 '(tab-line-tab ((t (:background "#504945" :foreground "#ebdbb2" :weight semi-bold :box (:line-width 1 :color "#665c54")))))
 '(tab-line-tab-current ((t (:background "#504945" :foreground "#fabd2f" :weight semi-bold :box (:line-width 1 :color "#665c54")))))
 '(tab-line-tab-inactive ((t (:background "#282828" :foreground "#928374" :box (:line-width 1 :color "#504945")))))
 '(tab-line-tab-modified ((t (:foreground "#fe8019"))))
 '(tab-line-highlight ((t (:background "#665c54" :foreground "#ebdbb2"))))
 '(tab-line-close-highlight ((t (:foreground "#fb4934"))))
 '(whitespace-space ((t (:foreground "#665c54" :background unspecified))))
 '(whitespace-hspace ((t (:foreground "#665c54" :background unspecified))))
 '(whitespace-tab ((t (:foreground "#665c54" :background unspecified))))
 '(whitespace-newline ((t (:foreground "#665c54" :background unspecified))))
 '(whitespace-trailing ((t (:foreground "#fb4934" :background "#402120"))))
 '(whitespace-line ((t (:foreground "#fb4934" :background "#402120"))))
 '(whitespace-space-before-tab ((t (:foreground "#fe8019" :background unspecified))))
 '(whitespace-space-after-tab ((t (:foreground "#fe8019" :background unspecified))))
 '(whitespace-indentation ((t (:foreground "#7c6f64" :background unspecified))))
 '(whitespace-empty ((t (:background "#402120"))))
 '(whitespace-missing-newline-at-eof ((t (:foreground "#fe8019"))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-keyword-face ((t (:foreground "#fb4934" :weight regular))))
 '(font-lock-type-face ((t (:foreground "#fabd2f" :weight regular))))
 '(font-lock-builtin-face ((t (:foreground "#fe8019" :weight regular))))
 '(font-lock-function-name-face ((t (:foreground "#b8bb26" :weight normal))))
 '(font-lock-function-call-face ((t (:foreground "#ebdbb2" :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#ebdbb2" :weight normal))))
 '(font-lock-variable-use-face ((t (:foreground "#ebdbb2" :weight normal))))
 '(font-lock-constant-face ((t (:foreground "#fe8019"))))
 '(font-lock-string-face ((t (:foreground "#b8bb26" :slant italic))))
 '(font-lock-doc-face ((t (:foreground "#928374" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#928374" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7c6f64" :slant italic))))
 '(font-lock-preprocessor-face ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(font-lock-warning-face ((t (:foreground "#fb4934" :weight bold))))
 '(font-lock-escape-face ((t (:foreground "#fabd2f"))))
 '(font-lock-operator-face ((t (:foreground "#ebdbb2" :weight normal))))
 '(font-lock-bracket-face ((t (:foreground "#fabd2f" :weight normal))))
 '(font-lock-delimiter-face ((t (:foreground "#d5c4a1"))))
 '(font-lock-punctuation-face ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(font-lock-property-name-face ((t (:foreground "#83a598" :weight normal))))
 '(font-lock-property-use-face ((t (:foreground "#83a598" :weight normal))))
 '(font-lock-number-face ((t (:foreground "#d3869b"))))
 '(font-lock-negation-char-face ((t (:foreground "#fe8019"))))
 '(treesit-fold-replacement-face ((t (:foreground "#928374" :box (:line-width 1 :color "#665c54")))))
 '(treesit-fold-fringe-face ((t (:foreground "#928374"))))
 '(font-lock-misc-punctuation-face ((t (:foreground "#8ec07c"))))
 '(smerge-lower ((t (:background "#34381b"))))
 '(smerge-upper ((t (:background "#402120"))))
 '(smerge-base ((t (:background "#0e363e"))))
 '(smerge-markers ((t (:background "#504945" :weight bold))))
 '(diff-added ((t (:background "#34381b" :foreground "#b8bb26"))))
 '(diff-removed ((t (:background "#402120" :foreground "#fb4934"))))
 '(diff-changed ((t (:background "#0e363e" :foreground "#83a598"))))
 '(diff-header ((t (:background "#504945" :foreground "#ebdbb2" :weight bold))))
 '(diff-file-header ((t (:background "#504945" :foreground "#ebdbb2" :weight bold))))
 '(diff-hunk-header ((t (:background "#504945" :foreground "#fabd2f"))))
 '(diff-hl-insert ((t (:foreground "#b8bb26" :background unspecified))))
 '(diff-hl-delete ((t (:foreground "#fb4934" :background unspecified))))
 '(diff-hl-change ((t (:foreground "#83a598" :background unspecified))))
 '(diff-hl-margin-insert ((t (:foreground "#b8bb26" :background unspecified))))
 '(diff-hl-margin-delete ((t (:foreground "#fb4934" :background unspecified))))
 '(diff-hl-margin-change ((t (:foreground "#83a598" :background unspecified))))
 '(diff-hl-reverted-hunk-highlight ((t (:background "#3B3116"))))
 '(magit-section-heading ((t (:foreground "#8ec07c" :weight semi-bold :extend t))))
 '(magit-section-heading-selection ((t (:foreground "#fe8019" :weight semi-bold :extend t))))
 '(magit-section-secondary-heading ((t (:foreground "#d3869b" :weight semi-bold :extend t))))
 '(magit-section-highlight ((t (:background "#3c3836" :extend t))))
 '(magit-filename ((t (:foreground "#d3869b" :weight regular))))
 '(magit-hash ((t (:foreground "#7c6f64"))))
 '(magit-tag ((t (:foreground "#fabd2f"))))
 '(magit-dimmed ((t (:foreground "#7c6f64"))))
 '(magit-diff-file-heading ((t (:foreground "#ebdbb2" :weight semi-bold :extend t))))
 '(magit-diff-file-heading-highlight ((t (:background "#3c3836" :weight semi-bold :extend t))))
 '(magit-diff-file-heading-selection ((t (:foreground "#d3869b" :background "#0e363e" :weight bold :extend t))))
 '(magit-diff-hunk-heading ((t (:background "#3c3836" :foreground "#928374" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#504945" :foreground "#ebdbb2" :weight semi-bold :extend t))))
 '(magit-diff-lines-heading ((t (:background "#fabd2f" :foreground "#282828" :extend t))))
 '(magit-diff-context ((t (:foreground "#7c6f64" :background "#282828" :extend t))))
 '(magit-diff-context-highlight ((t (:foreground "#ebdbb2" :background "#282828" :extend t))))
 '(magit-diff-added ((t (:foreground "#b8bb26" :extend t))))
 '(magit-diff-added-highlight ((t (:background "#34381b" :foreground "#b8bb26" :weight semi-bold :extend t))))
 '(magit-diff-removed ((t (:foreground "#fb4934" :extend t))))
 '(magit-diff-removed-highlight ((t (:background "#402120" :foreground "#fb4934" :weight semi-bold :extend t))))
 '(magit-diff-base ((t (:background "#0e363e" :foreground "#83a598" :extend t))))
 '(magit-diff-base-highlight ((t (:background "#0e363e" :foreground "#83a598" :weight semi-bold :extend t))))
 '(magit-diffstat-added ((t (:foreground "#b8bb26"))))
 '(magit-diffstat-removed ((t (:foreground "#fb4934"))))
 '(magit-branch-current ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(magit-branch-local ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(magit-branch-remote ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(magit-log-author ((t (:foreground "#fb4934"))))
 '(magit-log-date ((t (:foreground "#83a598"))))
 '(magit-log-graph ((t (:foreground "#7c6f64"))))
 '(magit-blame-heading ((t (:foreground "#fe8019" :background "#504945" :extend t))))
 '(magit-blame-hash ((t (:foreground "#8ec07c"))))
 '(magit-blame-date ((t (:foreground "#fb4934"))))
 '(magit-bisect-bad ((t (:foreground "#fb4934"))))
 '(magit-bisect-good ((t (:foreground "#b8bb26"))))
 '(magit-bisect-skip ((t (:foreground "#fe8019"))))
 '(magit-cherry-equivalent ((t (:foreground "#d3869b"))))
 '(magit-cherry-unmatched ((t (:foreground "#8ec07c"))))
 '(magit-reflog-amend ((t (:foreground "#d3869b"))))
 '(magit-reflog-checkout ((t (:foreground "#83a598"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#b8bb26"))))
 '(magit-reflog-commit ((t (:foreground "#b8bb26"))))
 '(magit-reflog-merge ((t (:foreground "#b8bb26"))))
 '(magit-reflog-other ((t (:foreground "#8ec07c"))))
 '(magit-reflog-rebase ((t (:foreground "#d3869b"))))
 '(magit-reflog-remote ((t (:foreground "#8ec07c"))))
 '(magit-reflog-reset ((t (:foreground "#fb4934" :weight semi-bold))))
 '(magit-sequence-drop ((t (:foreground "#fb4934"))))
 '(magit-sequence-head ((t (:foreground "#83a598"))))
 '(magit-sequence-part ((t (:foreground "#fe8019"))))
 '(magit-sequence-stop ((t (:foreground "#b8bb26"))))
 '(magit-signature-good ((t (:foreground "#b8bb26"))))
 '(magit-signature-bad ((t (:foreground "#fb4934" :weight semi-bold))))
 '(magit-signature-error ((t (:foreground "#fb4934"))))
 '(magit-signature-expired ((t (:foreground "#fe8019"))))
 '(magit-signature-revoked ((t (:foreground "#d3869b"))))
 '(magit-signature-untrusted ((t (:foreground "#fabd2f"))))
 '(magit-process-ok ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(magit-process-ng ((t (:foreground "#fb4934" :weight semi-bold))))
 '(git-commit-summary ((t (:foreground "#ebdbb2" :weight semi-bold))))
 '(git-commit-overlong-summary ((t (:foreground "#fb4934" :weight semi-bold))))
 '(git-commit-nonempty-second-line ((t (:foreground "#fb4934"))))
 '(git-commit-keyword ((t (:foreground "#8ec07c"))))
 '(git-commit-pseudo-header ((t (:foreground "#928374"))))
 '(git-commit-known-pseudo-header ((t (:foreground "#83a598" :weight semi-bold))))
 '(git-commit-comment-branch-local ((t (:foreground "#fabd2f"))))
 '(git-commit-comment-branch-remote ((t (:foreground "#b8bb26"))))
 '(git-commit-comment-heading ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(git-commit-comment-file ((t (:foreground "#d3869b"))))
 '(git-commit-comment-action ((t (:foreground "#fe8019"))))
 '(dired-directory ((t (:foreground "#83a598" :weight semi-bold))))
 '(dired-symlink ((t (:foreground "#8ec07c" :slant italic))))
 '(dired-flagged ((t (:foreground "#fb4934" :weight semi-bold))))
 '(dired-marked ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(dired-header ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(org-level-1 ((t (:inherit default :foreground "#ea6962" :weight bold))))
 '(org-level-2 ((t (:inherit default :foreground "#e78a4e" :weight bold))))
 '(org-level-3 ((t (:inherit default :foreground "#d8a657" :weight semi-bold))))
 '(org-level-4 ((t (:inherit default :foreground "#a9b665" :weight semi-bold))))
 '(org-level-5 ((t (:inherit default :foreground "#7daea3" :weight semi-bold))))
 '(org-level-6 ((t (:inherit default :foreground "#d3869b" :weight semi-bold))))
 '(org-level-7 ((t (:inherit default :foreground "#89b482" :weight semi-bold))))
 '(org-level-8 ((t (:inherit default :foreground "#d5be98" :weight semi-bold))))
 '(org-document-info-keyword ((t (:foreground "#a89984" :inherit fixed-pitch))))
 '(org-document-title ((t (:foreground "#ea6962" :weight semi-bold))))
 '(org-document-info ((t (:foreground "#ddc7a1"))))
 '(org-meta-line ((t (:foreground "#d8a657" :inherit fixed-pitch))))
 '(org-todo ((t (:foreground "#d8a657" :weight bold))))
 '(org-done ((t (:foreground "#928374" :weight bold))))
 '(org-headline-done ((t (:foreground "#928374" :strike-through t))))
 '(org-priority ((t (:foreground "#e78a4e"))))
 '(org-keyword ((t (:foreground "#d8a657" :weight semi-bold))))
 '(org-tag ((t (:foreground "#7c6f64" :slant italic))))
 '(org-tag-group ((t (:foreground "#a89984" :slant italic))))
 '(org-special-keyword ((t (:foreground "#a89984" :inherit fixed-pitch))))
 '(org-property-value ((t (:foreground "#d5be98" :inherit fixed-pitch))))
 '(org-block ((t (:background "#32302f" :extend t :inherit fixed-pitch :height 1.0))))
 '(org-block-begin-line ((t (:background "#32302f" :foreground "#7c6f64" :slant italic :extend t :inherit fixed-pitch :height 1.0))))
 '(org-block-end-line ((t (:background "#32302f" :foreground "#7c6f64" :slant italic :extend t :inherit fixed-pitch :height 1.0))))
 '(org-code ((t (:foreground "#89b482" :background "#32302f" :inherit fixed-pitch :height 1.0))))
 '(org-verbatim ((t (:foreground "#89b482" :background "#32302f" :inherit fixed-pitch :height 1.0))))
 '(org-link ((t (:foreground "#7daea3" :inherit fixed-pitch :underline t))))
 '(org-footnote ((t (:foreground "#7daea3" :underline t :slant italic))))
 '(org-table ((t (:foreground "#d5be98" :inherit fixed-pitch :height 1.0))))
 '(org-formula ((t (:foreground "#d8a657" :inherit fixed-pitch :height 1.0))))
 '(org-column ((t (:background "#32302f"))))
 '(org-column-title ((t (:background "#32302f" :weight bold :underline t))))
 '(org-date ((t (:foreground "#d3869b" :underline t :inherit fixed-pitch :height 1.0))))
 '(org-date-selected ((t (:foreground "#d8a657" :weight bold))))
 '(org-scheduled ((t (:foreground "#d5be98"))))
 '(org-scheduled-today ((t (:foreground "#a9b665" :weight semi-bold))))
 '(org-scheduled-previously ((t (:foreground "#ea6962"))))
 '(org-upcoming-deadline ((t (:foreground "#e78a4e"))))
 '(org-warning ((t (:foreground "#ea6962" :weight bold))))
 '(org-agenda-date ((t (:foreground "#a89984"))))
 '(org-agenda-date-today ((t (:foreground "#d8a657" :weight bold))))
 '(org-agenda-date-weekend ((t (:foreground "#a89984" :slant italic))))
 '(org-agenda-structure ((t (:foreground "#89b482" :weight bold))))
 '(org-agenda-done ((t (:foreground "#928374" :strike-through t))))
 '(org-agenda-clocking ((t (:background "#374141"))))
 '(org-agenda-current-time ((t (:foreground "#d8a657" :weight bold))))
 '(org-time-grid ((t (:foreground "#7c6f64"))))
 '(org-drawer ((t (:foreground "#7c6f64" :inherit fixed-pitch))))
 '(org-ellipsis ((t (:foreground "#7c6f64"))))
 '(org-hide ((t (:foreground "#282828"))))
 '(org-list-dt ((t (:foreground "#d8a657" :weight semi-bold))))
 '(org-checkbox ((t (:foreground "#d8a657" :weight bold :inherit fixed-pitch :height 1.0))))
 '(org-checkbox-statistics-todo ((t (:foreground "#d8a657" :weight bold))))
 '(org-checkbox-statistics-done ((t (:foreground "#a9b665" :weight bold))))
 '(Man-overstrike ((t (:foreground "#ebdbb2" :weight semi-bold))))
 '(Man-underline ((t (:foreground "#ebdbb2" :underline t))))
 '(Man-reverse ((t (:foreground "#fe8019" :weight bold))))
 '(info-title-1 ((t (:foreground "#fb4934" :weight bold :height 1.2))))
 '(info-title-2 ((t (:foreground "#fabd2f" :weight bold :height 1.1))))
 '(info-title-3 ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(info-title-4 ((t (:foreground "#83a598" :weight semi-bold))))
 '(info-header-node ((t (:foreground "#8ec07c" :weight bold))))
 '(info-header-xref ((t (:foreground "#83a598" :underline t))))
 '(info-node ((t (:foreground "#8ec07c" :weight bold :slant italic))))
 '(info-xref ((t (:foreground "#83a598" :underline t))))
 '(info-xref-visited ((t (:foreground "#d3869b" :underline t))))
 '(info-menu-header ((t (:foreground "#fabd2f" :weight bold))))
 '(info-menu-star ((t (:foreground "#fb4934"))))
 '(info-index-match ((t (:background "#34381b" :foreground "#b8bb26"))))
 '(ido-first-match ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(ido-only-match ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(ido-subdir ((t (:foreground "#83a598" :weight semi-bold))))
 '(ido-virtual ((t (:foreground "#928374" :slant italic))))
 '(ido-indicator ((t (:foreground "#fb4934" :weight bold))))
 '(ido-incomplete-regexp ((t (:foreground "#fe8019" :weight bold))))
 '(vertico-current ((t (:background "#3c3836" :foreground "#fbf1c7" :weight semi-bold))))
 '(orderless-match-face-0 ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(orderless-match-face-1 ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(orderless-match-face-2 ((t (:foreground "#d3869b" :weight semi-bold))))
 '(orderless-match-face-3 ((t (:foreground "#83a598" :weight semi-bold))))
 '(marginalia-key ((t (:foreground "#fabd2f"))))
 '(marginalia-type ((t (:foreground "#83a598"))))
 '(marginalia-char ((t (:foreground "#fabd2f"))))
 '(marginalia-date ((t (:foreground "#d3869b"))))
 '(marginalia-size ((t (:foreground "#928374"))))
 '(marginalia-file-name ((t (:foreground "#d5c4a1"))))
 '(marginalia-file-priv-no ((t (:foreground "#7c6f64"))))
 '(marginalia-documentation ((t (:foreground "#928374" :slant italic))))
 '(corfu-default ((t (:background "#3c3836" :foreground "#ebdbb2"))))
 '(corfu-current ((t (:background "#2D4F4F" :foreground "#fbf1c7" :weight semi-bold))))
 '(corfu-border ((t (:background "#665c54"))))
 '(corfu-bar ((t (:background "#928374"))))
 '(corfu-annotations ((t (:foreground "#928374"))))
 '(company-tooltip ((t (:background "#3c3836" :foreground "#ebdbb2"))))
 '(company-tooltip-common ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(company-tooltip-selection ((t (:background "#2D4F4F" :foreground "#fbf1c7" :weight semi-bold))))
 '(company-tooltip-common-selection ((t (:foreground "#8ec07c" :weight bold))))
 '(company-tooltip-search ((t (:background "#3B3116" :foreground "#fabd2f" :weight semi-bold))))
 '(company-tooltip-search-selection ((t (:background "#fabd2f" :foreground "#282828" :weight bold))))
 '(company-tooltip-annotation ((t (:foreground "#928374"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#fbf1c7"))))
 '(company-scrollbar-bg ((t (:background "#504945"))))
 '(company-scrollbar-fg ((t (:background "#a89984"))))
 '(company-preview ((t (:foreground "#d5c4a1"))))
 '(company-preview-common ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(company-preview-search ((t (:foreground "#fabd2f"))))
 '(company-echo-common ((t (:foreground "#8ec07c" :weight bold))))
 '(ivy-current-match ((t (:background "#504945" :weight semi-bold :extend t))))
 '(ivy-minibuffer-match-face-1 ((t (:foreground "#928374" :background nil))))
 '(ivy-minibuffer-match-face-2 ((t (:background nil :foreground "#fabd2f" :weight semi-bold))))
 '(ivy-minibuffer-match-face-3 ((t (:background nil :foreground "#8ec07c" :weight semi-bold))))
 '(ivy-minibuffer-match-face-4 ((t (:background nil :foreground "#d3869b" :weight semi-bold))))
 '(ivy-minibuffer-match-highlight ((t (:background nil :foreground "#fabd2f" :weight bold))))
 '(ivy-confirm-face ((t (:foreground "#b8bb26"))))
 '(ivy-match-required-face ((t (:foreground "#fb4934"))))
 '(ivy-highlight-face ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(ivy-separator ((t (:foreground "#665c54"))))
 '(ivy-prompt-match ((t (:foreground "#fb4934"))))
 '(ivy-subdir ((t (:foreground "#83a598" :weight semi-bold))))
 '(ivy-virtual ((t (:foreground "#928374" :slant italic))))
 '(ivy-remote ((t (:foreground "#8ec07c"))))
 '(ivy-modified-buffer ((t (:foreground "#fe8019"))))
 '(ivy-modified-outside-buffer ((t (:foreground "#fabd2f"))))
 '(ivy-action ((t (:foreground "#83a598" :weight semi-bold))))
 '(ivy-grep-info ((t (:foreground "#b8bb26"))))
 '(ivy-grep-line-number ((t (:foreground "#d3869b"))))
 '(ivy-rich-doc-face ((t (:foreground "#928374" :slant italic))))
 '(ivy-rich-path-face ((t (:foreground "#83a598"))))
 '(ivy-rich-annotation-face ((t (:foreground "#928374"))))
 '(ivy-rich-modifier-face ((t (:foreground "#fe8019"))))
 '(swiper-line-face ((t (:background "#504945" :weight semi-bold :extend t))))
 '(swiper-match-face-1 ((t (:foreground "#928374" :background nil))))
 '(swiper-match-face-2 ((t (:background nil :foreground "#fabd2f" :weight semi-bold))))
 '(swiper-match-face-3 ((t (:background nil :foreground "#8ec07c" :weight semi-bold))))
 '(swiper-match-face-4 ((t (:background nil :foreground "#d3869b" :weight semi-bold))))
 '(swiper-background-match-face-1 ((t (:foreground "#928374" :background nil))))
 '(swiper-background-match-face-2 ((t (:background nil :foreground "#fabd2f"))))
 '(swiper-background-match-face-3 ((t (:background nil :foreground "#8ec07c"))))
 '(swiper-background-match-face-4 ((t (:background nil :foreground "#d3869b"))))
 '(swiper-isearch-match ((t (:background nil :foreground "#fabd2f" :weight semi-bold))))
 '(swiper-isearch-match-highlight ((t (:background nil :foreground "#fbf1c7" :weight bold))))
 '(vterm-color-default ((t (:foreground "#ebdbb2" :background "#282828"))))
 '(vterm-color-black ((t (:foreground "#3c3836" :background "#7c6f64"))))
 '(vterm-color-red ((t (:foreground "#fb4934" :background "#fb4934"))))
 '(vterm-color-green ((t (:foreground "#b8bb26" :background "#b8bb26"))))
 '(vterm-color-yellow ((t (:foreground "#fabd2f" :background "#fabd2f"))))
 '(vterm-color-blue ((t (:foreground "#83a598" :background "#83a598"))))
 '(vterm-color-magenta ((t (:foreground "#d3869b" :background "#d3869b"))))
 '(vterm-color-cyan ((t (:foreground "#8ec07c" :background "#8ec07c"))))
 '(vterm-color-white ((t (:foreground "#ebdbb2" :background "#d5c4a1"))))
 '(vterm-color-bright-black ((t (:foreground "#928374" :background "#a89984"))))
 '(vterm-color-bright-red ((t (:foreground "#fb4934" :background "#fb4934"))))
 '(vterm-color-bright-green ((t (:foreground "#b8bb26" :background "#b8bb26"))))
 '(vterm-color-bright-yellow ((t (:foreground "#fabd2f" :background "#fabd2f"))))
 '(vterm-color-bright-blue ((t (:foreground "#83a598" :background "#83a598"))))
 '(vterm-color-bright-magenta ((t (:foreground "#d3869b" :background "#d3869b"))))
 '(vterm-color-bright-cyan ((t (:foreground "#8ec07c" :background "#8ec07c"))))
 '(vterm-color-bright-white ((t (:foreground "#fbf1c7" :background "#fbf1c7"))))
 '(vterm-color-underline ((t (:underline t))))
 '(vterm-color-inverse-video ((t (:foreground "#282828" :background "#ebdbb2"))))
 '(eshell-prompt ((t (:foreground "#b8bb26" :weight bold))))
 '(eshell-ls-directory ((t (:foreground "#83a598" :weight semi-bold))))
 '(eshell-ls-symlink ((t (:foreground "#8ec07c" :slant italic))))
 '(eshell-ls-executable ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(eshell-ls-archive ((t (:foreground "#fb4934" :weight semi-bold))))
 '(eshell-ls-readonly ((t (:foreground "#fb4934"))))
 '(eshell-ls-unreadable ((t (:foreground "#7c6f64"))))
 '(eshell-ls-special ((t (:foreground "#d3869b" :weight semi-bold))))
 '(eshell-ls-missing ((t (:foreground "#fb4934" :weight bold :underline t))))
 '(eshell-ls-product ((t (:foreground "#fabd2f"))))
 '(eshell-ls-clutter ((t (:foreground "#7c6f64"))))
 '(eshell-ls-backup ((t (:foreground "#928374"))))
 '(comint-highlight-prompt ((t (:foreground "#b8bb26" :weight bold))))
 '(comint-highlight-input ((t (:foreground "#fbf1c7"))))
 '(term ((t (:background "#282828" :foreground "#ebdbb2"))))
 '(term-color-black ((t (:foreground "#3c3836" :background "#7c6f64"))))
 '(term-color-red ((t (:foreground "#fb4934" :background "#fb4934"))))
 '(term-color-green ((t (:foreground "#b8bb26" :background "#b8bb26"))))
 '(term-color-yellow ((t (:foreground "#fabd2f" :background "#fabd2f"))))
 '(term-color-blue ((t (:foreground "#83a598" :background "#83a598"))))
 '(term-color-magenta ((t (:foreground "#d3869b" :background "#d3869b"))))
 '(term-color-cyan ((t (:foreground "#8ec07c" :background "#8ec07c"))))
 '(term-color-white ((t (:foreground "#ebdbb2" :background "#d5c4a1"))))
 '(term-color-bright-black ((t (:foreground "#928374" :background "#a89984"))))
 '(term-color-bright-red ((t (:foreground "#fb4934" :background "#fb4934"))))
 '(term-color-bright-green ((t (:foreground "#b8bb26" :background "#b8bb26"))))
 '(term-color-bright-yellow ((t (:foreground "#fabd2f" :background "#fabd2f"))))
 '(term-color-bright-blue ((t (:foreground "#83a598" :background "#83a598"))))
 '(term-color-bright-magenta ((t (:foreground "#d3869b" :background "#d3869b"))))
 '(term-color-bright-cyan ((t (:foreground "#8ec07c" :background "#8ec07c"))))
 '(term-color-bright-white ((t (:foreground "#fbf1c7" :background "#fbf1c7"))))
 '(term-underline ((t (:underline t))))
 '(powerline-active0 ((t (:background "#3A3735" :foreground "#ddc7a1"))))
 '(powerline-active1 ((t (:background "#45403d" :foreground "#ddc7a1"))))
 '(powerline-active2 ((t (:background "#5a524c" :foreground "#d4be98"))))
 '(powerline-inactive0 ((t (:background "#2B2B2B" :foreground "#928374"))))
 '(powerline-inactive1 ((t (:background "#32302f" :foreground "#928374"))))
 '(powerline-inactive2 ((t (:background "#45403d" :foreground "#7c6f64"))))
 '(powerline-evil-normal-face ((t (:background "#7daea3" :foreground "#282828" :weight bold))))
 '(powerline-evil-insert-face ((t (:background "#a9b665" :foreground "#282828" :weight bold))))
 '(powerline-evil-visual-face ((t (:background "#e78a4e" :foreground "#282828" :weight bold))))
 '(powerline-evil-replace-face ((t (:background "#ea6962" :foreground "#282828" :weight bold))))
 '(powerline-evil-operator-face ((t (:background "#d8a657" :foreground "#282828" :weight bold))))
 '(powerline-evil-motion-face ((t (:background "#d3869b" :foreground "#282828" :weight bold))))
 '(powerline-evil-emacs-face ((t (:background "#89b482" :foreground "#282828" :weight bold))))
 '(sml/global ((t (:background "#3A3735" :foreground "#d5be98"))))
 '(sml/modes ((t (:background "#3A3735" :foreground "#d5be98"))))
 '(sml/minor-modes ((t (:background "#3A3735" :foreground "#928374"))))
 '(sml/filename ((t (:foreground "#d8a657" :weight semi-bold))))
 '(sml/prefix ((t (:foreground "#89b482" :weight semi-bold))))
 '(sml/folder ((t (:foreground "#928374"))))
 '(sml/not-modified ((t (:foreground "#d5be98"))))
 '(sml/modified ((t (:foreground "#e78a4e" :weight bold))))
 '(sml/outside-modified ((t (:foreground "#ea6962" :weight bold))))
 '(sml/read-only ((t (:foreground "#7daea3" :weight semi-bold))))
 '(sml/remote ((t (:foreground "#89b482"))))
 '(sml/sudo ((t (:foreground "#ea6962" :weight bold))))
 '(sml/line-number ((t (:foreground "#ddc7a1" :weight semi-bold))))
 '(sml/col-number ((t (:foreground "#d5be98"))))
 '(sml/numbers-separator ((t (:foreground "#7c6f64"))))
 '(sml/position-percentage ((t (:foreground "#928374"))))
 '(sml/process ((t (:foreground "#89b482"))))
 '(sml/time ((t (:foreground "#928374"))))
 '(sml/client ((t (:foreground "#d3869b"))))
 '(sml/mule-info ((t (:foreground "#928374"))))
 '(sml/charging ((t (:foreground "#a9b665"))))
 '(sml/discharging ((t (:foreground "#e78a4e"))))
 '(sml/projectile-replacement-face ((t (:foreground "#89b482" :weight semi-bold))))
 '(eww-default-colors ((t (:background "#282828" :foreground "#ebdbb2"))))
 '(shr-h1 ((t (:foreground "#fb4934" :weight bold :height 1.3))))
 '(shr-h2 ((t (:foreground "#fe8019" :weight bold :height 1.2))))
 '(shr-h3 ((t (:foreground "#fabd2f" :weight semi-bold :height 1.1))))
 '(shr-h4 ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(shr-h5 ((t (:foreground "#83a598" :weight semi-bold))))
 '(shr-h6 ((t (:foreground "#d3869b"))))
 '(shr-link ((t (:foreground "#83a598" :underline t))))
 '(shr-selected-link ((t (:foreground "#282828" :background "#83a598" :weight bold))))
 '(eww-valid-certificate ((t (:foreground "#b8bb26" :weight semi-bold))))
 '(eww-invalid-certificate ((t (:foreground "#fb4934" :weight bold))))
 '(eww-form-url ((t (:foreground "#fbf1c7" :background "#3c3836" :box (:line-width 1 :color "#665c54")))))
 '(eww-form-text ((t (:foreground "#ebdbb2" :background "#504945" :box (:line-width 1 :color "#665c54")))))
 '(eww-form-textarea ((t (:foreground "#ebdbb2" :background "#504945" :box (:line-width 1 :color "#665c54")))))
 '(eww-form-select ((t (:foreground "#ebdbb2" :background "#504945" :box (:line-width 1 :color "#665c54")))))
 '(eww-form-submit ((t (:foreground "#282828" :background "#83a598" :weight semi-bold :box (:line-width 1 :color "#7c6f64")))))
 '(eww-form-file ((t (:foreground "#282828" :background "#8ec07c" :weight semi-bold :box (:line-width 1 :color "#7c6f64")))))
 '(eww-form-checkbox ((t (:foreground "#fabd2f" :background "#504945" :box (:line-width 1 :color "#665c54")))))
 '(shr-code ((t (:foreground "#8ec07c" :background "#3c3836" :box (:line-width 1 :color "#504945")))))
 '(shr-abbreviation ((t (:underline (:color "#928374")))))
 '(shr-strike-through ((t (:strike-through t :foreground "#928374"))))
 '(eww-history-url ((t (:foreground "#83a598" :underline t))))
 '(eww-history-title ((t (:foreground "#ebdbb2" :weight semi-bold))))
 '(markdown-header-face ((t (:inherit default :weight bold))))
 '(markdown-header-face-1 ((t (:inherit default :foreground "#fb4934" :weight bold :height 1.3))))
 '(markdown-header-face-2 ((t (:inherit default :foreground "#fe8019" :weight bold :height 1.2))))
 '(markdown-header-face-3 ((t (:inherit default :foreground "#fabd2f" :weight semi-bold :height 1.1))))
 '(markdown-header-face-4 ((t (:inherit default :foreground "#b8bb26" :weight semi-bold))))
 '(markdown-header-face-5 ((t (:inherit default :foreground "#83a598" :weight semi-bold))))
 '(markdown-header-face-6 ((t (:inherit default :foreground "#d3869b" :weight semi-bold))))
 '(markdown-header-delimiter-face ((t (:foreground "#7c6f64" :weight bold))))
 '(markdown-bold-face ((t (:foreground "#fbf1c7" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#fbf1c7" :slant italic))))
 '(markdown-strike-through-face ((t (:foreground "#928374" :strike-through t))))
 '(markdown-inline-code-face ((t (:foreground "#8ec07c" :background "#3c3836" :inherit fixed-pitch :height 1.0))))
 '(markdown-code-face ((t (:background "#3c3836" :extend t :inherit fixed-pitch :height 1.0))))
 '(markdown-pre-face ((t (:foreground "#fbf1c7" :background "#3c3836" :inherit fixed-pitch :height 1.0))))
 '(markdown-language-keyword-face ((t (:foreground "#7c6f64" :slant italic :inherit fixed-pitch :height 1.0))))
 '(markdown-link-face ((t (:foreground "#83a598" :underline t))))
 '(markdown-url-face ((t (:foreground "#83a598" :underline t))))
 '(markdown-link-title-face ((t (:foreground "#b8bb26"))))
 '(markdown-reference-face ((t (:foreground "#8ec07c"))))
 '(markdown-missing-link-face ((t (:foreground "#fb4934" :underline t :weight bold))))
 '(markdown-plain-url-face ((t (:foreground "#83a598" :underline t :slant italic))))
 '(markdown-angle-bracket-face ((t (:foreground "#8ec07c"))))
 '(markdown-list-face ((t (:foreground "#fabd2f" :weight semi-bold))))
 '(markdown-blockquote-face ((t (:foreground "#928374" :slant italic))))
 '(markdown-hr-face ((t (:foreground "#665c54" :weight bold))))
 '(markdown-yaml-key-face ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(markdown-yaml-value-face ((t (:foreground "#b8bb26"))))
 '(markdown-metadata-key-face ((t (:foreground "#8ec07c" :weight semi-bold))))
 '(markdown-metadata-value-face ((t (:foreground "#b8bb26"))))
 '(markdown-html-tag-name-face ((t (:foreground "#fb4934"))))
 '(markdown-html-tag-delimiter-face ((t (:foreground "#d5c4a1"))))
 '(markdown-html-attr-name-face ((t (:foreground "#fe8019"))))
 '(markdown-html-attr-value-face ((t (:foreground "#b8bb26"))))
 '(markdown-html-entity-face ((t (:foreground "#8ec07c"))))
 '(markdown-gfm-checkbox-face ((t (:foreground "#fabd2f" :weight bold :inherit fixed-pitch :height 1.0))))
 '(markdown-footnote-marker-face ((t (:foreground "#83a598" :weight semi-bold))))
 '(markdown-footnote-text-face ((t (:foreground "#d5c4a1" :slant italic))))
 '(markdown-table-face ((t (:foreground "#d5c4a1" :inherit fixed-pitch :height 1.0))))
 '(eldoc-highlight-function-argument ((t (:foreground "#fabd2f" :weight bold))))
 '(eldoc-box-body ((t (:background "#3c3836" :foreground "#ebdbb2"))))
 '(eldoc-box-border ((t (:background "#665c54"))))
 '(eldoc-box-scrollable-indicator ((t (:foreground "#928374"))))
 '(web-mode-html-tag-face ((t (:foreground "#fb4934"))))
 '(web-mode-html-attr-name-face ((t (:foreground "#fe8019"))))
 '(web-mode-html-attr-value-face ((t (:foreground "#b8bb26"))))
 '(flycheck-error ((t (:underline (:style wave :color "#fb4934")))))
 '(flycheck-warning ((t (:underline (:style wave :color "#fabd2f")))))
 '(flycheck-info ((t (:underline (:style wave :color "#83a598")))))
 '(anzu-mode-line ((t (:foreground "#fabd2f" :weight bold))))
 '(anzu-mode-line-no-match ((t (:foreground "#fb4934" :weight bold))))
 '(anzu-match-1 ((t (:background "#34381b" :foreground "#b8bb26"))))
 '(anzu-match-2 ((t (:background "#3B3116" :foreground "#fabd2f"))))
 '(anzu-match-3 ((t (:background "#0e363e" :foreground "#83a598"))))
 '(anzu-replace-to ((t (:foreground "#fe8019" :weight bold))))
 '(anzu-replace-highlight ((t (:background "#402120" :foreground "#fb4934" :weight bold))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#fabd2f"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#83a598"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#d3869b"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8ec07c"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#fe8019"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#b8bb26"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#fb4934"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#fb4934" :weight bold :underline t))))
 '(org-superstar-header-bullet ((t (:height 1.2)))))

(provide-theme 'gruvbox)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(provide 'gruvbox)
;;; gruvbox-theme.el ends here
