;;; gruvbox-material-theme.el --- Gruvbox Material theme (medium contrast, material palette) -*- lexical-binding: t -*-

;; Author: Ziad Ahmed

;;;###autoload
(deftheme gruvbox-material
  "Gruvbox Material Theme")

(let* (
       ;; Backgrounds (Gruvbox Material, medium contrast — sainnhe/gruvbox-material)
       (bg0 "#282828")
       (bg0-soft "#32302f")
       (bg1 "#3c3836")
       (bg2 "#45403d")
       (bg3 "#504945")
       (bg4 "#5a524c")
       ;; Foregrounds
       (fg-1 "#ddc7a1")
       (fg0 "#d4be98")
       (fg1 "#c9b593")
       (fg2 "#beab8e")
       (fg3 "#b3a289")
       (fg4 "#a89984")
       (gray "#928374")
       ;; Bright palette (Material foreground)
       (red "#ea6962")
       (orange "#e78a4e")
       (yellow "#d8a657")
       (green "#a9b665")
       (aqua "#89b482")
       (blue "#7daea3")
       (purple "#d3869b")
       ;; Faded backgrounds (diffs / search highlights)
       (bg-red "#402120")
       (bg-green "#34381b")
       (bg-yellow "#4f422e")
       (bg-blue "#0e363e")
       (bg-teal "#374141")
       ;; Mode-line / powerline
       (bg-statusline1 "#32302f")
       (bg-statusline2 "#1b1b1b")
       (bg-statusline3 "#504945")
       (bg-statusline4 "#5a524c")
       ;; Material accents (org headings, mode-line emphasis)
       (mat-red "#ea6962")
       (mat-orange "#e78a4e")
       (mat-yellow "#d8a657")
       (mat-green "#a9b665")
       (mat-aqua "#7daea3")
       (mat-teal "#89b482")
       (bg-mat-teal "#374141"))

  (custom-theme-set-faces
   'gruvbox-material
   `(default ((t (:background ,bg0 :foreground ,fg0))))
   `(bold    ((t (:inherit default :foreground ,blue :weight bold))))
   `(cursor ((t (:background ,fg0))))
   `(fringe ((t (:background ,bg0-soft :foreground ,bg4))))
   `(hl-line ((t (:background ,bg1))))
   `(region ((t (:background ,bg-teal))))
   `(secondary-selection ((t (:background ,bg2))))
   `(vertical-border ((t (:foreground ,bg2))))
   `(fill-column-indicator ((t (:background ,bg1 :foreground ,bg1))))
   `(minibuffer-prompt ((t (:foreground ,aqua :weight semi-bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(highlight ((t (:background ,bg-teal))))
   `(lazy-highlight ((t (:background ,bg-yellow :foreground ,fg0))))
   `(isearch ((t (:background ,bg-teal :foreground ,fg-1 :weight bold))))
   `(isearch-fail ((t (:background ,bg-red :foreground ,red))))
   `(match ((t (:background ,bg-green :foreground ,fg0))))
   `(show-paren-match ((t (:background ,bg-teal :foreground ,yellow :weight bold))))
   `(show-paren-mismatch ((t (:background ,bg-red :foreground ,red :weight bold))))
   `(shadow ((t (:foreground ,gray))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(button ((t (:foreground ,blue :underline t))))
   `(header-line ((t (:background ,bg1 :foreground ,fg0))))
   `(header-line-highlight ((t (:background ,bg3 :foreground ,fg0))))
   `(help-key-binding ((t (:foreground ,aqua :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(homoglyph ((t (:foreground ,aqua))))
   `(nobreak-hyphen ((t (:foreground ,red))))
   `(escape-glyph ((t (:foreground ,aqua))))
   `(completions-common-part ((t (:foreground ,fg0 :weight bold))))
   `(completions-first-difference ((t (:foreground ,yellow :weight bold))))
   `(completions-annotations ((t (:foreground ,bg4 :slant italic))))
   `(widget-field ((t (:background ,bg2 :foreground ,fg0))))
   `(widget-button ((t (:foreground ,blue :weight bold))))
   `(tooltip ((t (:background ,bg3 :foreground ,fg-1))))
   `(line-number ((t (:background ,bg0 :foreground ,bg4 :inherit fixed-pitch :height 1.0))))
   `(line-number-current-line ((t (:background ,bg0 :foreground ,yellow :weight bold :inherit fixed-pitch :height 1.0))))
   `(mode-line ((t (:background ,bg-statusline1 :foreground ,fg2 :box (:line-width 1 :color ,bg2)))))
   `(mode-line-inactive ((t (:background ,bg-statusline2 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(mode-line-buffer-id ((t (:foreground ,fg1 :weight semi-bold))))
   `(mode-line-emphasis ((t (:foreground ,fg1 :weight semi-bold))))
   `(mode-line-highlight ((t (:foreground ,mat-orange))))
   `(tab-bar ((t (:background ,bg0 :foreground ,gray))))
   `(tab-bar-tab ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-bar-tab-inactive ((t (:background ,bg0 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(tab-line ((t (:background ,bg0 :foreground ,gray))))
   `(tab-line-tab ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-line-tab-current ((t (:background ,bg2 :foreground ,yellow :weight semi-bold :box (:line-width 1 :color ,bg3)))))
   `(tab-line-tab-inactive ((t (:background ,bg0 :foreground ,gray :box (:line-width 1 :color ,bg2)))))
   `(tab-line-tab-modified ((t (:foreground ,orange))))
   `(tab-line-highlight ((t (:background ,bg3 :foreground ,fg0))))
   `(tab-line-close-highlight ((t (:foreground ,red))))
   `(whitespace-space ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-hspace ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-tab ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-newline ((t (:foreground ,bg3 :background unspecified))))
   `(whitespace-trailing ((t (:foreground ,red :background ,bg-red))))
   `(whitespace-line ((t (:foreground ,red :background ,bg-red))))
   `(whitespace-space-before-tab ((t (:foreground ,orange :background unspecified))))
   `(whitespace-space-after-tab ((t (:foreground ,orange :background unspecified))))
   `(whitespace-indentation ((t (:foreground ,bg4 :background unspecified))))
   `(whitespace-empty ((t (:background ,bg-red))))
   `(whitespace-missing-newline-at-eof ((t (:foreground ,orange))))
   `(font-lock-doc-markup-face ((t (:inherit font-lock-keyword-face))))
   `(font-lock-keyword-face ((t (:foreground ,red :weight regular))))
   `(font-lock-type-face ((t (:foreground ,yellow :weight regular))))
   `(font-lock-builtin-face ((t (:foreground ,orange :weight regular))))
   `(font-lock-function-name-face ((t (:foreground ,green :weight normal))))
   `(font-lock-function-call-face ((t (:foreground ,green :weight normal))))
   `(font-lock-variable-name-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-variable-use-face ((t (:foreground ,blue :weight normal))))
   `(font-lock-constant-face ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,green :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,gray :slant italic))))
   `(font-lock-comment-face ((t (:foreground ,gray :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,bg4 :slant italic))))
   `(font-lock-preprocessor-face ((t (:foreground ,aqua :weight semi-bold))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(font-lock-escape-face ((t (:foreground ,yellow))))
   `(font-lock-operator-face ((t (:foreground ,fg0 :weight normal))))
   `(font-lock-bracket-face ((t (:foreground ,yellow :weight normal))))
   `(font-lock-delimiter-face ((t (:foreground ,fg3))))
   `(font-lock-punctuation-face ((t (:foreground ,aqua :weight semi-bold))))
   `(font-lock-property-name-face ((t (:foreground ,blue :weight normal))))
   `(font-lock-property-use-face ((t (:foreground ,blue :weight normal))))
   `(font-lock-number-face ((t (:foreground ,purple))))
   `(font-lock-negation-char-face ((t (:foreground ,orange))))
   `(treesit-fold-replacement-face ((t (:foreground ,gray :box (:line-width 1 :color ,bg3)))))
   `(treesit-fold-fringe-face
     ((t (:foreground ,bg4 :background ,bg0-soft))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,aqua))))
   `(smerge-lower ((t (:background ,bg-green))))
   `(smerge-upper ((t (:background ,bg-red))))
   `(smerge-base ((t (:background ,bg-blue))))
   `(smerge-markers ((t (:background ,bg2 :weight bold))))
   `(diff-added ((t (:background ,bg-green :foreground ,green))))
   `(diff-removed ((t (:background ,bg-red :foreground ,red))))
   `(diff-changed ((t (:background ,bg-blue :foreground ,blue))))
   `(diff-header ((t (:background ,bg2 :foreground ,fg0 :weight bold))))
   `(diff-file-header ((t (:background ,bg2 :foreground ,fg0 :weight bold))))
   `(diff-hunk-header ((t (:background ,bg2 :foreground ,yellow))))
   `(diff-hl-insert
     ((t (:foreground ,green :background ,bg0-soft))))
   `(diff-hl-delete
     ((t (:foreground ,red :background ,bg0-soft))))
   `(diff-hl-change
     ((t (:foreground ,blue :background ,bg0-soft))))
   `(diff-hl-margin-insert
     ((t (:foreground ,green :background ,bg0-soft))))
   `(diff-hl-margin-delete
     ((t (:foreground ,red :background ,bg0-soft))))
   `(diff-hl-margin-change
     ((t (:foreground ,blue :background ,bg0-soft))))
   `(diff-hl-reverted-hunk-highlight ((t (:background ,bg-yellow))))
   `(magit-section-heading ((t (:foreground ,aqua :weight semi-bold :extend t))))
   `(magit-section-heading-selection ((t (:foreground ,orange :weight semi-bold :extend t))))
   `(magit-section-secondary-heading ((t (:foreground ,purple :weight semi-bold :extend t))))
   `(magit-section-highlight ((t (:background ,bg1 :extend t))))
   `(magit-filename ((t (:foreground ,purple :weight regular))))
   `(magit-hash ((t (:foreground ,bg4))))
   `(magit-tag ((t (:foreground ,yellow))))
   `(magit-dimmed ((t (:foreground ,bg4))))
   `(magit-diff-file-heading ((t (:foreground ,fg0 :weight semi-bold :extend t))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg1 :weight semi-bold :extend t))))
   `(magit-diff-file-heading-selection ((t (:foreground ,purple :background ,bg-blue :weight bold :extend t))))
   `(magit-diff-hunk-heading ((t (:background ,bg1 :foreground ,gray :extend t))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg2 :foreground ,fg0 :weight semi-bold :extend t))))
   `(magit-diff-lines-heading ((t (:background ,yellow :foreground ,bg0 :extend t))))
   `(magit-diff-context ((t (:foreground ,bg4 :background ,bg0 :extend t))))
   `(magit-diff-context-highlight ((t (:foreground ,fg0 :background ,bg0 :extend t))))
   `(magit-diff-added ((t (:foreground ,green :extend t))))
   `(magit-diff-added-highlight ((t (:background ,bg-green :foreground ,green :weight semi-bold :extend t))))
   `(magit-diff-removed ((t (:foreground ,red :extend t))))
   `(magit-diff-removed-highlight ((t (:background ,bg-red :foreground ,red :weight semi-bold :extend t))))
   `(magit-diff-base ((t (:background ,bg-blue :foreground ,blue :extend t))))
   `(magit-diff-base-highlight ((t (:background ,bg-blue :foreground ,blue :weight semi-bold :extend t))))
   `(magit-diffstat-added ((t (:foreground ,green))))
   `(magit-diffstat-removed ((t (:foreground ,red))))
   `(magit-branch-current ((t (:foreground ,yellow :weight semi-bold))))
   `(magit-branch-local ((t (:foreground ,yellow :weight semi-bold))))
   `(magit-branch-remote ((t (:foreground ,green :weight semi-bold))))
   `(magit-log-author ((t (:foreground ,red))))
   `(magit-log-date ((t (:foreground ,blue))))
   `(magit-log-graph ((t (:foreground ,bg4))))
   `(magit-blame-heading ((t (:foreground ,orange :background ,bg2 :extend t))))
   `(magit-blame-hash ((t (:foreground ,aqua))))
   `(magit-blame-date ((t (:foreground ,red))))
   `(magit-bisect-bad ((t (:foreground ,red))))
   `(magit-bisect-good ((t (:foreground ,green))))
   `(magit-bisect-skip ((t (:foreground ,orange))))
   `(magit-cherry-equivalent ((t (:foreground ,purple))))
   `(magit-cherry-unmatched ((t (:foreground ,aqua))))
   `(magit-reflog-amend ((t (:foreground ,purple))))
   `(magit-reflog-checkout ((t (:foreground ,blue))))
   `(magit-reflog-cherry-pick ((t (:foreground ,green))))
   `(magit-reflog-commit ((t (:foreground ,green))))
   `(magit-reflog-merge ((t (:foreground ,green))))
   `(magit-reflog-other ((t (:foreground ,aqua))))
   `(magit-reflog-rebase ((t (:foreground ,purple))))
   `(magit-reflog-remote ((t (:foreground ,aqua))))
   `(magit-reflog-reset ((t (:foreground ,red :weight semi-bold))))
   `(magit-sequence-drop ((t (:foreground ,red))))
   `(magit-sequence-head ((t (:foreground ,blue))))
   `(magit-sequence-part ((t (:foreground ,orange))))
   `(magit-sequence-stop ((t (:foreground ,green))))
   `(magit-signature-good ((t (:foreground ,green))))
   `(magit-signature-bad ((t (:foreground ,red :weight semi-bold))))
   `(magit-signature-error ((t (:foreground ,red))))
   `(magit-signature-expired ((t (:foreground ,orange))))
   `(magit-signature-revoked ((t (:foreground ,purple))))
   `(magit-signature-untrusted ((t (:foreground ,yellow))))
   `(magit-process-ok ((t (:foreground ,green :weight semi-bold))))
   `(magit-process-ng ((t (:foreground ,red :weight semi-bold))))
   `(git-commit-summary ((t (:foreground ,fg0 :weight semi-bold))))
   `(git-commit-overlong-summary ((t (:foreground ,red :weight semi-bold))))
   `(git-commit-nonempty-second-line ((t (:foreground ,red))))
   `(git-commit-keyword ((t (:foreground ,aqua))))
   `(git-commit-pseudo-header ((t (:foreground ,gray))))
   `(git-commit-known-pseudo-header ((t (:foreground ,blue :weight semi-bold))))
   `(git-commit-comment-branch-local ((t (:foreground ,yellow))))
   `(git-commit-comment-branch-remote ((t (:foreground ,green))))
   `(git-commit-comment-heading ((t (:foreground ,aqua :weight semi-bold))))
   `(git-commit-comment-file ((t (:foreground ,purple))))
   `(git-commit-comment-action ((t (:foreground ,orange))))
   `(dired-directory ((t (:foreground ,blue :weight semi-bold))))
   `(dired-symlink ((t (:foreground ,aqua :slant italic))))
   `(dired-flagged ((t (:foreground ,red :weight semi-bold))))
   `(dired-marked ((t (:foreground ,yellow :weight semi-bold))))
   `(dired-header ((t (:foreground ,green :weight semi-bold))))
   `(org-level-1 ((t (:inherit default :foreground ,mat-red :weight bold))))
   `(org-level-2 ((t (:inherit default :foreground ,mat-orange :weight bold))))
   `(org-level-3 ((t (:inherit default :foreground ,mat-yellow :weight semi-bold))))
   `(org-level-4 ((t (:inherit default :foreground ,mat-green :weight semi-bold))))
   `(org-level-5 ((t (:inherit default :foreground ,mat-aqua :weight semi-bold))))
   `(org-level-6 ((t (:inherit default :foreground ,purple :weight semi-bold))))
   `(org-level-7 ((t (:inherit default :foreground ,mat-teal :weight semi-bold))))
   `(org-level-8 ((t (:inherit default :foreground ,fg2 :weight semi-bold))))
   `(org-document-info-keyword ((t (:foreground ,fg4 :inherit fixed-pitch))))
   `(org-document-title ((t (:foreground ,mat-red :weight semi-bold :height 1.1))))
   `(org-document-info ((t (:foreground ,fg1))))
   `(org-meta-line ((t (:foreground ,mat-yellow :inherit fixed-pitch))))
   `(org-todo ((t (:foreground ,mat-yellow :weight bold))))
   `(org-done ((t (:foreground ,gray :weight bold))))
   `(org-headline-done ((t (:foreground ,gray :strike-through t))))
   `(org-priority ((t (:foreground ,mat-orange))))
   `(org-keyword ((t (:foreground ,mat-yellow :weight semi-bold))))
   `(org-tag ((t (:foreground ,bg4 :slant italic))))
   `(org-tag-group ((t (:foreground ,fg4 :slant italic))))
   `(org-special-keyword ((t (:foreground ,fg4 :inherit fixed-pitch))))
   `(org-property-value ((t (:foreground ,fg2 :inherit fixed-pitch))))
   `(org-block ((t (:background ,bg0-soft :extend t :inherit fixed-pitch :height 1.0))))
   `(org-block-begin-line ((t (:background ,bg0-soft :foreground ,bg4 :slant italic :extend t :inherit fixed-pitch :height 1.0))))
   `(org-block-end-line ((t (:background ,bg0-soft :foreground ,bg4 :slant italic :extend t :inherit fixed-pitch :height 1.0))))
   `(org-code ((t (:foreground ,mat-teal :background ,bg0-soft :inherit fixed-pitch :height 1.0))))
   `(org-verbatim ((t (:foreground ,mat-teal :background ,bg0-soft :inherit fixed-pitch :height 1.0))))
   `(org-link ((t (:foreground ,mat-aqua :inherit fixed-pitch :underline t))))
   `(org-footnote ((t (:foreground ,mat-aqua :underline t :slant italic))))
   `(org-table ((t (:foreground ,fg2 :inherit fixed-pitch :height 1.0))))
   `(org-formula ((t (:foreground ,mat-yellow :inherit fixed-pitch :height 1.0))))
   `(org-column ((t (:background ,bg0-soft))))
   `(org-column-title ((t (:background ,bg0-soft :weight bold :underline t))))
   `(org-date ((t (:foreground ,purple :underline t :inherit fixed-pitch :height 1.0))))
   `(org-date-selected ((t (:foreground ,mat-yellow :weight bold))))
   `(org-scheduled ((t (:foreground ,fg2))))
   `(org-scheduled-today ((t (:foreground ,mat-green :weight semi-bold))))
   `(org-scheduled-previously ((t (:foreground ,mat-red))))
   `(org-upcoming-deadline ((t (:foreground ,mat-orange))))
   `(org-warning ((t (:foreground ,mat-red :weight bold))))
   `(org-agenda-date ((t (:foreground ,fg4))))
   `(org-agenda-date-today ((t (:foreground ,mat-yellow :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,fg4 :slant italic))))
   `(org-agenda-structure ((t (:foreground ,mat-teal :weight bold))))
   `(org-agenda-done ((t (:foreground ,gray :strike-through t))))
   `(org-agenda-clocking ((t (:background ,bg-mat-teal))))
   `(org-agenda-current-time ((t (:foreground ,mat-yellow :weight bold))))
   `(org-time-grid ((t (:foreground ,bg4))))
   `(org-drawer ((t (:foreground ,bg4 :inherit fixed-pitch))))
   `(org-ellipsis ((t (:foreground ,bg4))))
   `(org-hide ((t (:foreground ,bg0))))
   `(org-list-dt ((t (:foreground ,mat-yellow :weight semi-bold))))
   `(org-checkbox ((t (:foreground ,mat-yellow :weight bold :inherit fixed-pitch :height 1.0))))
   `(org-checkbox-statistics-todo ((t (:foreground ,mat-yellow :weight bold))))
   `(org-checkbox-statistics-done ((t (:foreground ,mat-green :weight bold))))
   `(Man-overstrike ((t (:foreground ,fg0 :weight semi-bold))))
   `(Man-underline ((t (:foreground ,fg0 :underline t))))
   `(Man-reverse ((t (:foreground ,orange :weight bold))))
   `(info-title-1 ((t (:foreground ,red :weight bold :height 1.2))))
   `(info-title-2 ((t (:foreground ,yellow :weight bold :height 1.1))))
   `(info-title-3 ((t (:foreground ,green :weight semi-bold))))
   `(info-title-4 ((t (:foreground ,blue :weight semi-bold))))
   `(info-header-node ((t (:foreground ,aqua :weight bold))))
   `(info-header-xref ((t (:foreground ,blue :underline t))))
   `(info-node ((t (:foreground ,aqua :weight bold :slant italic))))
   `(info-xref ((t (:foreground ,blue :underline t))))
   `(info-xref-visited ((t (:foreground ,purple :underline t))))
   `(info-menu-header ((t (:foreground ,yellow :weight bold))))
   `(info-menu-star ((t (:foreground ,red))))
   `(info-index-match ((t (:background ,bg-green :foreground ,green))))
   `(ido-first-match ((t (:foreground ,yellow :weight semi-bold))))
   `(ido-only-match ((t (:foreground ,green :weight semi-bold))))
   `(ido-subdir ((t (:foreground ,blue :weight semi-bold))))
   `(ido-virtual ((t (:foreground ,gray :slant italic))))
   `(ido-indicator ((t (:foreground ,red :weight bold))))
   `(ido-incomplete-regexp ((t (:foreground ,orange :weight bold))))
   `(vertico-current ((t (:background ,bg1 :foreground ,fg-1 :weight semi-bold))))
   `(orderless-match-face-0 ((t (:background ,bg1 :foreground ,yellow :weight semi-bold))))
   `(orderless-match-face-1 ((t (:background ,bg1 :foreground ,aqua :weight semi-bold))))
   `(orderless-match-face-2 ((t (:background ,bg1 :foreground ,purple :weight semi-bold))))
   `(orderless-match-face-3 ((t (:background ,bg1 :foreground ,blue :weight semi-bold))))
   `(marginalia-key ((t (:foreground ,yellow))))
   `(marginalia-type ((t (:foreground ,blue))))
   `(marginalia-char ((t (:foreground ,yellow))))
   `(marginalia-date ((t (:foreground ,purple))))
   `(marginalia-size ((t (:foreground ,gray))))
   `(marginalia-file-name ((t (:foreground ,fg3))))
   `(marginalia-file-priv-no ((t (:foreground ,bg4))))
   `(marginalia-documentation ((t (:foreground ,gray :slant italic))))
   `(corfu-default ((t (:background ,bg1 :foreground ,fg0))))
   `(corfu-current ((t (:background ,bg2 :foreground ,fg-1 :weight semi-bold))))
   `(corfu-border ((t (:background ,bg3))))
   `(corfu-bar ((t (:background ,gray))))
   `(corfu-annotations ((t (:foreground ,gray))))
   `(company-tooltip ((t (:background ,bg1 :foreground ,fg0))))
   `(company-tooltip-common ((t (:foreground ,blue :weight semi-bold))))
   `(company-tooltip-selection ((t (:background ,bg2 :foreground ,fg-1 :weight semi-bold))))
   `(company-tooltip-common-selection ((t (:foreground ,blue :weight bold))))
   `(company-tooltip-search ((t (:background ,bg-yellow :foreground ,yellow :weight semi-bold))))
   `(company-tooltip-search-selection ((t (:background ,yellow :foreground ,bg0 :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,gray))))
   `(company-tooltip-annotation-selection ((t (:foreground ,fg-1))))
   `(company-scrollbar-bg ((t (:background ,bg2))))
   `(company-scrollbar-fg ((t (:background ,fg4))))
   `(company-preview ((t (:foreground ,fg3))))
   `(company-preview-common ((t (:foreground ,aqua :weight semi-bold))))
   `(company-preview-search ((t (:foreground ,yellow))))
   `(company-echo-common ((t (:foreground ,aqua :weight bold))))
   `(ivy-current-match ((t (:background ,bg2 :weight semi-bold :extend t))))
   `(ivy-minibuffer-match-face-1 ((t (:foreground ,gray :background nil))))
   `(ivy-minibuffer-match-face-2 ((t (:background nil :foreground ,yellow :weight semi-bold))))
   `(ivy-minibuffer-match-face-3 ((t (:background nil :foreground ,aqua :weight semi-bold))))
   `(ivy-minibuffer-match-face-4 ((t (:background nil :foreground ,purple :weight semi-bold))))
   `(ivy-minibuffer-match-highlight ((t (:background nil :foreground ,yellow :weight bold))))
   `(ivy-confirm-face ((t (:foreground ,green))))
   `(ivy-match-required-face ((t (:foreground ,red))))
   `(ivy-highlight-face ((t (:foreground ,aqua :weight semi-bold))))
   `(ivy-separator ((t (:foreground ,bg3))))
   `(ivy-prompt-match ((t (:foreground ,red))))
   `(ivy-subdir ((t (:foreground ,blue :weight semi-bold))))
   `(ivy-virtual ((t (:foreground ,gray :slant italic))))
   `(ivy-remote ((t (:foreground ,aqua))))
   `(ivy-modified-buffer ((t (:foreground ,orange))))
   `(ivy-modified-outside-buffer ((t (:foreground ,yellow))))
   `(ivy-action ((t (:foreground ,blue :weight semi-bold))))
   `(ivy-grep-info ((t (:foreground ,green))))
   `(ivy-grep-line-number ((t (:foreground ,purple))))
   `(ivy-rich-doc-face ((t (:foreground ,gray :slant italic))))
   `(ivy-rich-path-face ((t (:foreground ,blue))))
   `(ivy-rich-annotation-face ((t (:foreground ,gray))))
   `(ivy-rich-modifier-face ((t (:foreground ,orange))))
   `(swiper-line-face ((t (:background ,bg2 :weight semi-bold :extend t))))
   `(swiper-match-face-1 ((t (:foreground ,gray :background nil))))
   `(swiper-match-face-2 ((t (:background nil :foreground ,yellow :weight semi-bold))))
   `(swiper-match-face-3 ((t (:background nil :foreground ,aqua :weight semi-bold))))
   `(swiper-match-face-4 ((t (:background nil :foreground ,purple :weight semi-bold))))
   `(swiper-background-match-face-1 ((t (:foreground ,gray :background nil))))
   `(swiper-background-match-face-2 ((t (:background nil :foreground ,yellow))))
   `(swiper-background-match-face-3 ((t (:background nil :foreground ,aqua))))
   `(swiper-background-match-face-4 ((t (:background nil :foreground ,purple))))
   `(swiper-isearch-match ((t (:background nil :foreground ,yellow :weight semi-bold))))
   `(swiper-isearch-match-highlight ((t (:background nil :foreground ,fg-1 :weight bold))))
   `(vterm-color-default ((t (:foreground ,fg0 :background ,bg0))))
   `(vterm-color-black ((t (:foreground ,bg1 :background ,bg4))))
   `(vterm-color-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(vterm-color-blue ((t (:foreground ,blue :background ,blue))))
   `(vterm-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(vterm-color-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(vterm-color-white ((t (:foreground ,fg0 :background ,fg3))))
   `(vterm-color-bright-black ((t (:foreground ,gray :background ,fg4))))
   `(vterm-color-bright-red ((t (:foreground ,red :background ,red))))
   `(vterm-color-bright-green ((t (:foreground ,green :background ,green))))
   `(vterm-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(vterm-color-bright-blue ((t (:foreground ,blue :background ,blue))))
   `(vterm-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(vterm-color-bright-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(vterm-color-bright-white ((t (:foreground ,fg-1 :background ,fg-1))))
   `(vterm-color-underline ((t (:underline t))))
   `(vterm-color-inverse-video ((t (:foreground ,bg0 :background ,fg0))))
   `(eshell-prompt ((t (:foreground ,green :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,blue :weight semi-bold))))
   `(eshell-ls-symlink ((t (:foreground ,aqua :slant italic))))
   `(eshell-ls-executable ((t (:foreground ,green :weight semi-bold))))
   `(eshell-ls-archive ((t (:foreground ,red :weight semi-bold))))
   `(eshell-ls-readonly ((t (:foreground ,red))))
   `(eshell-ls-unreadable ((t (:foreground ,bg4))))
   `(eshell-ls-special ((t (:foreground ,purple :weight semi-bold))))
   `(eshell-ls-missing ((t (:foreground ,red :weight bold :underline t))))
   `(eshell-ls-product ((t (:foreground ,yellow))))
   `(eshell-ls-clutter ((t (:foreground ,bg4))))
   `(eshell-ls-backup ((t (:foreground ,gray))))
   `(comint-highlight-prompt ((t (:foreground ,green :weight bold))))
   `(comint-highlight-input ((t (:foreground ,fg-1))))
   `(term ((t (:background ,bg0 :foreground ,fg0))))
   `(term-color-black ((t (:foreground ,bg1 :background ,bg4))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-blue ((t (:foreground ,blue :background ,blue))))
   `(term-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(term-color-white ((t (:foreground ,fg0 :background ,fg3))))
   `(term-color-bright-black ((t (:foreground ,gray :background ,fg4))))
   `(term-color-bright-red ((t (:foreground ,red :background ,red))))
   `(term-color-bright-green ((t (:foreground ,green :background ,green))))
   `(term-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(term-color-bright-blue ((t (:foreground ,blue :background ,blue))))
   `(term-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-bright-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(term-color-bright-white ((t (:foreground ,fg-1 :background ,fg-1))))
   `(term-underline ((t (:underline t))))
   `(powerline-active0 ((t (:background ,bg-statusline1 :foreground ,fg1))))
   `(powerline-active1 ((t (:background ,bg-statusline3 :foreground ,fg1))))
   `(powerline-active2 ((t (:background ,bg-statusline4 :foreground ,fg2))))
   `(powerline-inactive0 ((t (:background ,bg-statusline2 :foreground ,gray))))
   `(powerline-inactive1 ((t (:background ,bg0-soft :foreground ,gray))))
   `(powerline-inactive2 ((t (:background ,bg-statusline3 :foreground ,bg4))))
   `(powerline-evil-normal-face ((t (:background ,mat-aqua :foreground ,bg0 :weight bold))))
   `(powerline-evil-insert-face ((t (:background ,mat-green :foreground ,bg0 :weight bold))))
   `(powerline-evil-visual-face ((t (:background ,mat-orange :foreground ,bg0 :weight bold))))
   `(powerline-evil-replace-face ((t (:background ,mat-red :foreground ,bg0 :weight bold))))
   `(powerline-evil-operator-face ((t (:background ,mat-yellow :foreground ,bg0 :weight bold))))
   `(powerline-evil-motion-face ((t (:background ,purple :foreground ,bg0 :weight bold))))
   `(powerline-evil-emacs-face ((t (:background ,mat-teal :foreground ,bg0 :weight bold))))
   `(sml/global ((t (:background ,bg-statusline1 :foreground ,fg2))))
   `(sml/modes ((t (:background ,bg-statusline1 :foreground ,fg2))))
   `(sml/minor-modes ((t (:background ,bg-statusline1 :foreground ,gray))))
   `(sml/filename ((t (:foreground ,mat-yellow :weight semi-bold))))
   `(sml/prefix ((t (:foreground ,mat-teal :weight semi-bold))))
   `(sml/folder ((t (:foreground ,gray))))
   `(sml/not-modified ((t (:foreground ,fg2))))
   `(sml/modified ((t (:foreground ,mat-orange :weight bold))))
   `(sml/outside-modified ((t (:foreground ,mat-red :weight bold))))
   `(sml/read-only ((t (:foreground ,mat-aqua :weight semi-bold))))
   `(sml/remote ((t (:foreground ,mat-teal))))
   `(sml/sudo ((t (:foreground ,mat-red :weight bold))))
   `(sml/line-number ((t (:foreground ,fg1 :weight semi-bold))))
   `(sml/col-number ((t (:foreground ,fg2))))
   `(sml/numbers-separator ((t (:foreground ,bg4))))
   `(sml/position-percentage ((t (:foreground ,gray))))
   `(sml/process ((t (:foreground ,mat-teal))))
   `(sml/time ((t (:foreground ,gray))))
   `(sml/client ((t (:foreground ,purple))))
   `(sml/mule-info ((t (:foreground ,gray))))
   `(sml/charging ((t (:foreground ,mat-green))))
   `(sml/discharging ((t (:foreground ,mat-orange))))
   `(sml/projectile-replacement-face ((t (:foreground ,mat-teal :weight semi-bold))))
   `(eww-default-colors ((t (:background ,bg0 :foreground ,fg0))))
   `(shr-h1 ((t (:foreground ,red :weight bold :height 1.3))))
   `(shr-h2 ((t (:foreground ,orange :weight bold :height 1.2))))
   `(shr-h3 ((t (:foreground ,yellow :weight semi-bold :height 1.1))))
   `(shr-h4 ((t (:foreground ,green :weight semi-bold))))
   `(shr-h5 ((t (:foreground ,blue :weight semi-bold))))
   `(shr-h6 ((t (:foreground ,purple))))
   `(shr-link ((t (:foreground ,blue :underline t))))
   `(shr-selected-link ((t (:foreground ,bg0 :background ,blue :weight bold))))
   `(eww-valid-certificate ((t (:foreground ,green :weight semi-bold))))
   `(eww-invalid-certificate ((t (:foreground ,red :weight bold))))
   `(eww-form-url ((t (:foreground ,fg-1 :background ,bg1 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-text ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-textarea ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-select ((t (:foreground ,fg0 :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(eww-form-submit ((t (:foreground ,bg0 :background ,blue :weight semi-bold :box (:line-width 1 :color ,bg4)))))
   `(eww-form-file ((t (:foreground ,bg0 :background ,aqua :weight semi-bold :box (:line-width 1 :color ,bg4)))))
   `(eww-form-checkbox ((t (:foreground ,yellow :background ,bg2 :box (:line-width 1 :color ,bg3)))))
   `(shr-code ((t (:foreground ,aqua :background ,bg1 :box (:line-width 1 :color ,bg2)))))
   `(shr-abbreviation ((t (:underline (:color ,gray)))))
   `(shr-strike-through ((t (:strike-through t :foreground ,gray))))
   `(eww-history-url ((t (:foreground ,blue :underline t))))
   `(eww-history-title ((t (:foreground ,fg0 :weight semi-bold))))
   `(markdown-header-face ((t (:inherit default :weight bold))))
   `(markdown-header-face-1 ((t (:inherit default :foreground ,red :weight bold :height 1.3))))
   `(markdown-header-face-2 ((t (:inherit default :foreground ,orange :weight bold :height 1.2))))
   `(markdown-header-face-3 ((t (:inherit default :foreground ,yellow :weight normal))))
   `(markdown-header-face-4 ((t (:inherit default :foreground ,green :weight normal))))
   `(markdown-header-face-5 ((t (:inherit default :foreground ,blue :weight normal))))
   `(markdown-header-face-6 ((t (:inherit default :foreground ,purple :weight normal))))
   `(markdown-header-delimiter-face ((t (:foreground ,bg4 :weight bold))))
   `(markdown-bold-face ((t (:foreground ,fg-1 :weight bold))))
   `(markdown-italic-face ((t (:foreground ,fg-1 :slant italic))))
   `(markdown-strike-through-face ((t (:foreground ,gray :strike-through t))))
   `(markdown-inline-code-face ((t (:foreground ,aqua :background ,bg1 :inherit fixed-pitch :height 1.0))))
   `(markdown-code-face ((t (:background ,bg1 :extend t :inherit fixed-pitch :height 1.0))))
   `(markdown-pre-face ((t (:foreground ,fg-1 :background ,bg1 :inherit fixed-pitch :height 1.0))))
   `(markdown-language-keyword-face ((t (:foreground ,bg4 :slant italic :inherit fixed-pitch :height 1.0))))
   `(markdown-link-face ((t (:inherit default :underline t))))
   `(markdown-url-face ((t (:foreground ,blue :underline t))))
   `(markdown-link-title-face ((t (:foreground ,green))))
   `(markdown-reference-face ((t (:foreground ,aqua))))
   `(markdown-missing-link-face ((t (:foreground ,red :underline t :weight bold))))
   `(markdown-plain-url-face ((t (:foreground ,blue :underline t :slant italic))))
   `(markdown-angle-bracket-face ((t (:foreground ,aqua))))
   `(markdown-list-face ((t (:foreground ,yellow :weight semi-bold))))
   `(markdown-blockquote-face ((t (:foreground ,gray :slant italic))))
   `(markdown-hr-face ((t (:foreground ,bg3 :weight bold))))
   `(markdown-yaml-key-face ((t (:foreground ,aqua :weight semi-bold))))
   `(markdown-yaml-value-face ((t (:foreground ,green))))
   `(markdown-metadata-key-face ((t (:foreground ,aqua :weight semi-bold))))
   `(markdown-metadata-value-face ((t (:foreground ,green))))
   `(markdown-html-tag-name-face ((t (:foreground ,red))))
   `(markdown-html-tag-delimiter-face ((t (:foreground ,fg3))))
   `(markdown-html-attr-name-face ((t (:foreground ,orange))))
   `(markdown-html-attr-value-face ((t (:foreground ,green))))
   `(markdown-html-entity-face ((t (:foreground ,aqua))))
   `(markdown-gfm-checkbox-face ((t (:foreground ,yellow :weight bold :inherit fixed-pitch :height 1.0))))
   `(markdown-footnote-marker-face ((t (:foreground ,blue :weight semi-bold))))
   `(markdown-footnote-text-face ((t (:foreground ,fg3 :slant italic))))
   `(markdown-table-face ((t (:foreground ,fg3 :inherit fixed-pitch :height 1.0))))
   `(eldoc-highlight-function-argument ((t (:foreground ,yellow :weight normal))))
   `(eldoc-box-body ((t (:background ,bg1 :foreground ,fg0))))
   `(eldoc-box-border ((t (:background ,bg3))))
   `(eldoc-box-scrollable-indicator ((t (:foreground ,gray))))
   `(web-mode-html-tag-face ((t (:foreground ,aqua :weight normal))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,gray))))
   `(web-mode-html-tag-namespaced-face ((t (:foreground ,orange))))
   `(web-mode-html-attr-name-face ((t (:foreground ,orange))))
   `(web-mode-html-attr-equal-face ((t (:foreground ,fg0))))
   `(web-mode-html-attr-value-face ((t (:foreground ,green :slant italic))))
   `(web-mode-html-attr-custom-face ((t (:foreground ,purple))))
   `(web-mode-html-attr-engine-face ((t (:foreground ,aqua))))
   `(web-mode-html-entity-face ((t (:foreground ,aqua))))
   `(web-mode-doctype-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-server-comment-face ((t (:foreground ,bg4 :slant italic))))
   `(web-mode-css-selector-face ((t (:foreground ,yellow :weight semi-bold))))
   `(web-mode-css-selector-class-face ((t (:foreground ,yellow))))
   `(web-mode-css-selector-tag-face ((t (:foreground ,red))))
   `(web-mode-css-pseudo-class-face ((t (:foreground ,purple))))
   `(web-mode-css-at-rule-face ((t (:foreground ,aqua :weight semi-bold))))
   `(web-mode-css-property-name-face ((t (:foreground ,blue))))
   `(web-mode-css-color-face ((t (:foreground ,purple))))
   `(web-mode-css-priority-face ((t (:foreground ,red :weight bold))))
   `(web-mode-css-function-face ((t (:foreground ,green))))
   `(web-mode-css-variable-face ((t (:foreground ,aqua :slant italic))))
   `(web-mode-css-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-css-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-json-key-face ((t (:foreground ,blue))))
   `(web-mode-json-context-face ((t (:foreground ,gray))))
   `(web-mode-javascript-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-javascript-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-function-call-face ((t (:foreground ,fg0))))
   `(web-mode-block-face ((t (:background ,bg0-soft :extend t))))
   `(web-mode-block-delimiter-face ((t (:foreground ,orange :weight bold))))
   `(web-mode-block-control-face ((t (:foreground ,red :weight semi-bold))))
   `(web-mode-block-comment-face ((t (:foreground ,gray :slant italic))))
   `(web-mode-block-string-face ((t (:foreground ,green :slant italic))))
   `(web-mode-part-face ((t (:background ,bg0))))
   `(web-mode-current-element-highlight-face ((t (:background ,bg2 :weight semi-bold))))
   `(web-mode-current-column-highlight-face ((t (:background ,bg1))))
   `(web-mode-whitespace-face ((t (:background ,bg-red))))
   `(web-mode-error-face ((t (:foreground ,red :underline (:style wave :color ,red)))))
   `(web-mode-warning-face ((t (:foreground ,yellow :underline (:style wave :color ,yellow)))))
   `(web-mode-folded-face ((t (:underline t))))
   `(anzu-mode-line                    ((t (:foreground ,yellow :weight bold))))
   `(anzu-mode-line-no-match           ((t (:foreground ,red :weight bold))))
   `(anzu-match-1                      ((t (:background ,bg-green :foreground ,green))))
   `(anzu-match-2                      ((t (:background ,bg-yellow :foreground ,yellow))))
   `(anzu-match-3                      ((t (:background ,bg-blue :foreground ,blue))))
   `(anzu-replace-to                   ((t (:foreground ,orange :weight bold))))
   `(anzu-replace-highlight            ((t (:background ,bg-red :foreground ,red :weight bold))))
   ;; Eglot
   `(eglot-highlight-symbol-face ((t (:background ,bg1 :inherit nil))))
   `(eglot-mode-line ((t (:foreground ,green :weight semi-bold))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:inherit shadow))))
   `(eglot-diagnostic-tag-deprecated-face ((t (:strike-through t :inherit shadow))))
   `(eglot-parameter-hint-face ((t (:inherit eglot-inlay-hint-face :foreground ,aqua))))
   `(eglot-type-hint-face ((t (:inherit eglot-inlay-hint-face :foreground ,purple))))
   ;; flymake
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-error-echo ((t (:foreground ,red))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-warning-echo ((t (:foreground ,yellow :weight normal))))
   `(flymake-note ((t (:underline (:style wave :color ,blue)))))
   `(flymake-note-echo ((t (:foreground ,blue :weight normal))))
   ;; flycheck
   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,blue)))))
   `(flycheck-fringe-error ((t (:foreground ,red :weight bold))))
   `(flycheck-fringe-warning ((t (:foreground ,yellow :weight bold))))
   `(flycheck-fringe-info ((t (:foreground ,blue :weight bold))))
   `(flycheck-error-list-error ((t (:foreground ,red :weight semi-bold))))
   `(flycheck-error-list-warning ((t (:foreground ,yellow :weight semi-bold))))
   `(flycheck-error-list-info ((t (:foreground ,blue :weight semi-bold))))
   `(flycheck-error-list-line-number ((t (:foreground ,purple))))
   `(flycheck-error-list-column-number ((t (:foreground ,purple))))
   `(flycheck-error-list-filename ((t (:foreground ,aqua :weight semi-bold))))
   `(flycheck-error-list-highlight ((t (:background ,bg1 :extend t))))
   `(flycheck-error-list-checker-name ((t (:foreground ,green))))
   `(flycheck-error-list-id ((t (:foreground ,gray))))
   `(flycheck-error-list-id-with-explainer ((t (:foreground ,gray :underline t))))
   `(flycheck-verify-select-checker ((t (:box (:line-width 1 :color ,bg3)))))
   ;; flycheck-inline
   `(flycheck-inline-error ((t (:foreground ,red :slant italic :height 0.9))))
   `(flycheck-inline-warning ((t (:foreground ,yellow :slant italic :height 0.9))))
   `(flycheck-inline-info ((t (:foreground ,blue :slant italic :height 0.9))))
   ;; lsp-mode
   `(lsp-face-highlight-textual ((t (:background ,bg1))))
   `(lsp-face-highlight-read ((t (:background ,bg1))))
   `(lsp-face-highlight-write ((t (:background ,bg2))))
   `(lsp-headerline-breadcrumb-default-face ((t (:foreground ,fg4 :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-path-face ((t (:foreground ,fg3 :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-symbols-face ((t (:foreground ,fg2 :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-separator-face ((t (:foreground ,bg4 :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-project-prefix-face ((t (:foreground ,blue :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-unknown-project-prefix-face ((t (:foreground ,red :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-path-error-face ((t (:underline (:style wave :color ,red) :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-path-warning-face ((t (:underline (:style wave :color ,yellow) :inherit fixed-pitch))))
   `(lsp-headerline-breadcrumb-path-info-face ((t (:underline (:style wave :color ,blue) :inherit fixed-pitch))))
   `(lsp-lens-face ((t (:foreground ,gray :height 0.9 :slant italic))))
   `(lsp-flycheck-warning-unnecessary-face ((t (:foreground ,gray :underline (:style wave :color ,yellow)))))
   ;; lsp-ui
   `(lsp-ui-doc-background ((t (:background ,bg1))))
   `(lsp-ui-doc-border ((t (:background ,bg3))))
   `(lsp-ui-sideline-code-action ((t (:foreground ,mat-yellow))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,yellow :weight semi-bold))))
   `(lsp-ui-sideline-symbol ((t (:foreground ,gray))))
   `(lsp-ui-sideline-symbol-info ((t (:foreground ,gray :height 0.9))))
   `(lsp-ui-peek-peek ((t (:background ,bg0))))
   `(lsp-ui-peek-list ((t (:background ,bg0))))
   `(lsp-ui-peek-filename ((t (:foreground ,blue :weight semi-bold))))
   `(lsp-ui-peek-header ((t (:background ,bg2 :foreground ,fg0))))
   `(lsp-ui-peek-selection ((t (:background ,bg2))))
   `(lsp-ui-peek-highlight ((t (:background ,bg-yellow :foreground ,fg0))))
   ;; Inlay hints
   `(eglot-inlay-hint-face ((t (:foreground ,gray :slant italic :height 0.9))))
   ;; Code actions
   `(eglot-code-action-indicator-face ((t (:foreground ,mat-yellow :weight normal))))
   `(eldoc-highlight-function-argument ((t (:foreground ,yellow :weight normal))))
   `(xref-match ((t (:background ,bg-teal :foreground ,fg-1 :weight semi-bold))))
   `(xref-file-header ((t (:foreground ,mat-orange :weight semi-bold))))
   `(org-superstar-header-bullet ((t (:height 1.2))))))

(defun gruvbox-material--remap-fringe ()
  (face-remap-add-relative 'fringe
                           :background "#282828"))

(dolist (hook '(minibuffer-setup-hook
                eshell-mode-hook
                magit-mode-hook
                compilation-mode-hook))
  (add-hook hook #'gruvbox-material--remap-fringe))


(provide-theme 'gruvbox-material)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(provide 'gruvbox-material)
;;; gruvbox-material-theme.el ends here
